### ISSUE TITLE
How to train MAML with ResNet-12?

### ISSUE THREAD

**Issue by hu-my** [baiksung/MeTAL#6]
Hi, I want to know how to train baseline MAML with ResNet-12 in your project, could you tell me the corresponding command?

**Comment by baiksung** [comment]
Hi,
Sorry for the late reply. I've been occupied with other works.
You should create a new config file copied from `experiment_config/MeTAL.json` and set `"meta_loss": false`, set `"backbone": "ResNet12"` and change `"experiment_name"` correspondingly for 5-way 5-shot classification.
Hope this helps!

Best,
Sungyong
