### ISSUE TITLE
How to get $GPU_ID when training the model?

### ISSUE THREAD

**Issue by yewanzhuo** [baiksung/MeTAL#7]
How to get $GPU_ID when training the model?
![@N1T`V~P`0A0(50 R{RJFOK](https://user-images.githubusercontent.com/112409010/187229552-207eedde-17f2-44c6-951e-8f7db6608e41.png)

**Comment by baiksung** [comment]
Hi,

That's just a GPU ID number. For example, if you are using GPU with ID 0, your comand would be `bash MeTAL.sh 0`.
Hope this helps.
