### ISSUE TITLE
Is it correct to use meta_loss in y = self.apply_inner_loop_update(loss=meta_loss, ...?

### ISSUE THREAD

**Issue by efsunsezer** [baiksung/MeTAL#8]
Hi,

I could not understand why meta_loss is used during the inner loop update process. Isn't it necessary to use support loss here?

Thank you.

**Comment by baiksung** [comment]
Hi,

This is a meta-learned loss function, which is a component introduced in this paper.
Note that meta_loss is not referring to a loss function you would normally use in the outer-loop optimization
meta_loss is a meta-learned loss function that can be beneficial in learning a new task during inner-loop optimization.
Please refer to Algorithm 2 and Section 3.2.2 in the paper.

Best,
Sungyong

**Comment by efsunsezer** [comment]
That "Note that meta_loss is not referring to a loss function you would normally use in the outer-loop optimization" is my answer.
Thank you for your help.
